/*
 * GLayProgressMonitor.java
 *
 * Created on June 30, 2008, 2:13 PM
 * 
 * Monitors the progress of the clustering process
 */

package glay.util;

/**
 *
 * @author  sugang
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.beans.*;
import java.util.Random;
import cytoscape.Cytoscape;

/*This progressBar listens*/
public class GLayProgressMonitor extends javax.swing.JPanel implements PropertyChangeListener{

    private ProgressMonitor progressMonitor;
    private Task task;
    
    class Task extends SwingWorker<Void, Void>{
        public Void doInBackground(){
        Random random = new Random();
            int progress = 0;
            setProgress(0);
            try {
                Thread.sleep(1000);
                System.out.println("Executing...");
                while (progress < 100 && !isCancelled()) {
                    //Sleep for up to one second.
                    Thread.sleep(random.nextInt(1000));
                    //Make random progress.
                    progress += random.nextInt(10);
                    setProgress(Math.min(progress, 100));
                }
            } catch (InterruptedException ignore) {}
            return null;

        }
        
        public void done(){
            progressMonitor.setProgress(0);
        }
    
    }
    
    
    /** Creates new form GLayProgressMonitor */
    public GLayProgressMonitor() {
        initComponents();
        System.out.println("Progress bar created.");
        
        //invoke when it's created
        this.progressMonitor = new ProgressMonitor(Cytoscape.getDesktop(), "Executing", "exe...", 0, 100);
        progressMonitor.setProgress(0);
        task = new Task();
        task.addPropertyChangeListener(this);
        task.execute();
        
        
    }
    
    public void propertyChange(PropertyChangeEvent evt){
        String progressString = new String("progress");
        //progressString.equalsIgnoreCase(evt.getPropertyName());
        //"progress" == evt.getPropertyName()
        
        //propertychangeevent has values..omg, how am i supposed to know this
        
        
        if (progressString.equalsIgnoreCase(evt.getPropertyName())){
            int progress = (Integer) evt.getNewValue();
            //this.progressBar.setValue(progress);
            this.progressMonitor.setProgress(progress);
            String message = String.format("Completed %d%%.\n", progress);
            progressMonitor.setNote(message);

        } 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Progress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

}
